---
title: "about"
author: "Linfeng"
date: "2022-12-10"
output: html_document
---
## Author

- **Name: ** Linfeng Wang
- **NetID: ** linfeng7
- **Email: ** linfeng7@illinois.edu

## Purpose

This APP is used to find singers that has songs ranked in the top 200 
on the Spotify and their relevant information. Hope you will enjoy it!


## Data

1. Highest Charting Position: The highest position that the song has been on in the Spotify Top 200 Weekly Global Charts in 2020 & 2021.

2. Number of Times Charted: The number of times that the song has been on in the Spotify Top 200 Weekly Global Charts in 2020 & 2021.

3. Week of Highest Charting: The week when the song had the Highest Position in the Spotify Top 200 Weekly Global Charts in 2020 & 2021.

4. Song Name: Name of the song that has been on in the Spotify Top 200 Weekly Global Charts in 2020 & 2021.

5. Song iD: The song ID provided by Spotify (unique to each song).

6. Streams: Approximate number of streams the song has.

7. Artist: The main artist/ artists involved in making the song.

8. Artist Followers: The number of followers the main artist has on Spotify.

9. Genre: The genres the song belongs to.

10. Release Date: The initial date that the song was released.

11. Weeks Charted: The weeks that the song has been on in the Spotify Top 200 Weekly Global Charts in 2020 & 2021.

12. Popularity:The popularity of the track. The value will be between 0 and 100, with 100 being the most popular.

13. Danceability: Danceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.

14. Acousticness: A measure from 0.0 to 1.0 of whether the track is acoustic.

15. Energy: Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy.

16. Instrumentalness: Predicts whether a track contains no vocals. The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content.

17. Liveness: Detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live.

18. Loudness: The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track. Values typical range between -60 and 0 db.

19. Speechiness: Speechiness detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value.

20. Tempo: The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.

21. Valence: A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).

22. Chord: The main chord of the song instrumental.


## Reference 

- [dataset from Kaggle](https://www.kaggle.com/datasets/sashankpillai/spotify-top-200-charts-20202021)


